#include <Raindrop/Graphics/GUI/Item.hpp>
#include <Raindrop/Graphics/GUI/Widgets/Frame.hpp>
#include <Raindrop/Graphics/GUI/Widgets/Button.hpp>
#include <Raindrop/Graphics/GUI/Widgets/Child.hpp>
#include <Raindrop/Graphics/GUI/Widgets/Separator.hpp>
#include <Raindrop/Graphics/GUI/Widgets/SameLine.hpp>
#include <Raindrop/Graphics/GUI/Widgets/Dummy.hpp>
#include <Raindrop/Graphics/GUI/Widgets/Indent.hpp>
#include <Raindrop/Graphics/GUI/Widgets/Unindent.hpp>
#include <Raindrop/Graphics/GUI/Widgets/Group.hpp>
#include <Raindrop/Graphics/GUI/Widgets/Text.hpp>
#include <Raindrop/Graphics/GUI/Widgets/DragInt.hpp>
#include <Raindrop/Graphics/GUI/Widgets/DragFloat.hpp>
#include <Raindrop/Graphics/GUI/Widgets/DragVec2.hpp>
#include <Raindrop/Graphics/GUI/Widgets/DragVec3.hpp>
#include <Raindrop/Graphics/GUI/Widgets/DragVec4.hpp>
#include <Raindrop/Graphics/GUI/Commands/Set.hpp>
#include <Raindrop/Graphics/GUI/Commands/SetFloat.hpp>
#include <Raindrop/Graphics/GUI/Commands/SetInt.hpp>
#include <Raindrop/Graphics/GUI/Commands/SetBool.hpp>
#include <Raindrop/Graphics/GUI/Commands/Open.hpp>
#include <Raindrop/Graphics/GUI/Commands/OpenChild.hpp>

namespace Raindrop::Graphics::GUI{
	using Constructor = std::unique_ptr<Item>(*)(tinyxml2::XMLElement* element, Core::Registry::Registry& registry, Core::Event::EventManager& _eventManager);
	#define widget_constructor(T) [](tinyxml2::XMLElement* _element, Core::Registry::Registry& _registry, Core::Event::EventManager& _eventManager){return (std::unique_ptr<Item>)std::move(std::make_unique<Widgets::T>(_element, _registry, _eventManager));}
	#define command_constructor(T) [](tinyxml2::XMLElement* _element, Core::Registry::Registry& _registry, Core::Event::EventManager& _eventManager){return (std::unique_ptr<Item>)std::move(std::make_unique<Commands::T>(_element, _registry, _eventManager));}

	std::unique_ptr<Item> Item::create(tinyxml2::XMLElement* element, Core::Registry::Registry& registry, Core::Event::EventManager& eventManager){
		static const std::unordered_map<std::string, Constructor> map{
			{"Frame", widget_constructor(Frame)},
			{"Button", widget_constructor(Button)},
			{"Child", widget_constructor(Child)},
			{"Separator", widget_constructor(Separator)},
			{"SameLine", widget_constructor(SameLine)},
			{"Dummy", widget_constructor(Dummy)},
			{"Indent", widget_constructor(Indent)},
			{"Unindent", widget_constructor(Unindent)},
			{"Group", widget_constructor(Group)},
			{"Text", widget_constructor(Text)},
			{"DragInt", widget_constructor(DragInt)},
			{"DragFloat", widget_constructor(DragFloat)},
			{"DragVec2", widget_constructor(DragVec2)},
			{"DragVec3", widget_constructor(DragVec3)},
			{"DragVec4", widget_constructor(DragVec4)},

			{"Set", command_constructor(Set)},
			{"SetInt", command_constructor(SetInt)},
			{"SetFloat", command_constructor(SetFloat)},
			{"SetBool", command_constructor(SetBool)},
			{"Open", command_constructor(Open)},
			{"OpenChild", command_constructor(OpenChild)},
		};

		auto it = map.find(element->Name());
		if (it == map.end()){
			CLOG(ERROR, "Engine.Graphics.GUI") << "Cannot reconize " << element->Name() << " Item type : skiped";
			return nullptr;
		}

		return it->second(element, registry, eventManager);
	}

	ImGuiWindowFlags Item::strToFlags(const std::string& str){
		static const std::unordered_map<std::string, int> map{
			{"ImGuiWindowFlags_None", ImGuiWindowFlags_None },
			{"ImGuiWindowFlags_NoTitleBar", ImGuiWindowFlags_NoTitleBar },
			{"ImGuiWindowFlags_NoResize", ImGuiWindowFlags_NoResize },
			{"ImGuiWindowFlags_NoMove", ImGuiWindowFlags_NoMove },
			{"ImGuiWindowFlags_NoScrollbar", ImGuiWindowFlags_NoScrollbar },
			{"ImGuiWindowFlags_NoScrollWithMouse", ImGuiWindowFlags_NoScrollWithMouse },
			{"ImGuiWindowFlags_NoCollapse", ImGuiWindowFlags_NoCollapse },
			{"ImGuiWindowFlags_AlwaysAutoResize", ImGuiWindowFlags_AlwaysAutoResize },
			{"ImGuiWindowFlags_NoBackground", ImGuiWindowFlags_NoBackground },
			{"ImGuiWindowFlags_NoSavedSettings", ImGuiWindowFlags_NoSavedSettings },
			{"ImGuiWindowFlags_NoMouseInputs", ImGuiWindowFlags_NoMouseInputs },
			{"ImGuiWindowFlags_MenuBar", ImGuiWindowFlags_MenuBar },
			{"ImGuiWindowFlags_HorizontalScrollbar", ImGuiWindowFlags_HorizontalScrollbar },
			{"ImGuiWindowFlags_NoFocusOnAppearing", ImGuiWindowFlags_NoFocusOnAppearing },
			{"ImGuiWindowFlags_NoBringToFrontOnFocus", ImGuiWindowFlags_NoBringToFrontOnFocus },
			{"ImGuiWindowFlags_AlwaysVerticalScrollbar", ImGuiWindowFlags_AlwaysVerticalScrollbar },
			{"ImGuiWindowFlags_AlwaysHorizontalScrollbar", ImGuiWindowFlags_AlwaysHorizontalScrollbar },
			{"ImGuiWindowFlags_AlwaysUseWindowPadding", ImGuiWindowFlags_AlwaysUseWindowPadding },
			{"ImGuiWindowFlags_NoNavInputs", ImGuiWindowFlags_NoNavInputs },
			{"ImGuiWindowFlags_NoNavFocus", ImGuiWindowFlags_NoNavFocus },
			{"ImGuiWindowFlags_UnsavedDocument", ImGuiWindowFlags_UnsavedDocument },
			{"ImGuiWindowFlags_NoNav", ImGuiWindowFlags_NoNav },
			{"ImGuiWindowFlags_NoDecoration", ImGuiWindowFlags_NoDecoration },
			{"ImGuiWindowFlags_NoInputs", ImGuiWindowFlags_NoInputs },
			{"ImGuiWindowFlags_NavFlattened", ImGuiWindowFlags_NavFlattened },
			{"ImGuiWindowFlags_ChildWindow", ImGuiWindowFlags_ChildWindow },
			{"ImGuiWindowFlags_Tooltip", ImGuiWindowFlags_Tooltip },
			{"ImGuiWindowFlags_Popup", ImGuiWindowFlags_Popup },
			{"ImGuiWindowFlags_Modal", ImGuiWindowFlags_Modal },
			{"ImGuiWindowFlags_ChildMenu", ImGuiWindowFlags_ChildMenu },

			//InputText flags
			{"ImGuiInputTextFlags_None", ImGuiInputTextFlags_None},
			{"ImGuiInputTextFlags_CharsDecimal", ImGuiInputTextFlags_CharsDecimal},
			{"ImGuiInputTextFlags_CharsHexadecimal", ImGuiInputTextFlags_CharsHexadecimal},
			{"ImGuiInputTextFlags_CharsUppercase", ImGuiInputTextFlags_CharsUppercase},
			{"ImGuiInputTextFlags_CharsNoBlank", ImGuiInputTextFlags_CharsNoBlank},
			{"ImGuiInputTextFlags_AutoSelectAll", ImGuiInputTextFlags_AutoSelectAll},
			{"ImGuiInputTextFlags_EnterReturnsTrue", ImGuiInputTextFlags_EnterReturnsTrue},
			{"ImGuiInputTextFlags_CallbackCompletion", ImGuiInputTextFlags_CallbackCompletion},
			{"ImGuiInputTextFlags_CallbackHistory", ImGuiInputTextFlags_CallbackHistory},
			{"ImGuiInputTextFlags_CallbackAlways", ImGuiInputTextFlags_CallbackAlways},
			{"ImGuiInputTextFlags_CallbackCharFilter", ImGuiInputTextFlags_CallbackCharFilter},
			{"ImGuiInputTextFlags_AllowTabInput", ImGuiInputTextFlags_AllowTabInput},
			{"ImGuiInputTextFlags_CtrlEnterForNewLine", ImGuiInputTextFlags_CtrlEnterForNewLine},
			{"ImGuiInputTextFlags_NoHorizontalScroll", ImGuiInputTextFlags_NoHorizontalScroll},
			{"ImGuiInputTextFlags_ReadOnly", ImGuiInputTextFlags_ReadOnly},
			{"ImGuiInputTextFlags_Password", ImGuiInputTextFlags_Password},
			{"ImGuiInputTextFlags_NoUndoRedo", ImGuiInputTextFlags_NoUndoRedo},
			{"ImGuiInputTextFlags_CharsScientific", ImGuiInputTextFlags_CharsScientific},
			{"ImGuiInputTextFlags_CallbackResize", ImGuiInputTextFlags_CallbackResize},
			{"ImGuiInputTextFlags_CallbackEdit", ImGuiInputTextFlags_CallbackEdit},

			//TreeNode Flags
			{"ImGuiTreeNodeFlags_None", ImGuiTreeNodeFlags_None},
			{"ImGuiTreeNodeFlags_Selected", ImGuiTreeNodeFlags_Selected},
			{"ImGuiTreeNodeFlags_Framed", ImGuiTreeNodeFlags_Framed},
			{"ImGuiTreeNodeFlags_AllowItemOverlap", ImGuiTreeNodeFlags_AllowItemOverlap},
			{"ImGuiTreeNodeFlags_NoTreePushOnOpen", ImGuiTreeNodeFlags_NoTreePushOnOpen},
			{"ImGuiTreeNodeFlags_NoAutoOpenOnLog", ImGuiTreeNodeFlags_NoAutoOpenOnLog},
			{"ImGuiTreeNodeFlags_DefaultOpen", ImGuiTreeNodeFlags_DefaultOpen},
			{"ImGuiTreeNodeFlags_OpenOnDoubleClick", ImGuiTreeNodeFlags_OpenOnDoubleClick},
			{"ImGuiTreeNodeFlags_OpenOnArrow", ImGuiTreeNodeFlags_OpenOnArrow},
			{"ImGuiTreeNodeFlags_Leaf", ImGuiTreeNodeFlags_Leaf},
			{"ImGuiTreeNodeFlags_Bullet", ImGuiTreeNodeFlags_Bullet},
			{"ImGuiTreeNodeFlags_FramePadding", ImGuiTreeNodeFlags_FramePadding},
			{"ImGuiTreeNodeFlags_SpanAvailWidth", ImGuiTreeNodeFlags_SpanAvailWidth},
			{"ImGuiTreeNodeFlags_SpanFullWidth", ImGuiTreeNodeFlags_SpanFullWidth},
			{"ImGuiTreeNodeFlags_NavLeftJumpsBackHere", ImGuiTreeNodeFlags_NavLeftJumpsBackHere},
			{"ImGuiTreeNodeFlags_CollapsingHeader", ImGuiTreeNodeFlags_CollapsingHeader},

			//enum ImGuiPopupFlags_
			{"ImGuiPopupFlags_None", ImGuiPopupFlags_None},
			{"ImGuiPopupFlags_MouseButtonLeft", ImGuiPopupFlags_MouseButtonLeft},
			{"ImGuiPopupFlags_MouseButtonRight", ImGuiPopupFlags_MouseButtonRight},
			{"ImGuiPopupFlags_MouseButtonMiddle", ImGuiPopupFlags_MouseButtonMiddle},
			{"ImGuiPopupFlags_MouseButtonMask_", ImGuiPopupFlags_MouseButtonMask_},
			{"ImGuiPopupFlags_MouseButtonDefault_", ImGuiPopupFlags_MouseButtonDefault_},
			{"ImGuiPopupFlags_NoOpenOverExistingPopup", ImGuiPopupFlags_NoOpenOverExistingPopup},
			{"ImGuiPopupFlags_NoOpenOverItems", ImGuiPopupFlags_NoOpenOverItems},
			{"ImGuiPopupFlags_AnyPopupId", ImGuiPopupFlags_AnyPopupId},
			{"ImGuiPopupFlags_AnyPopupLevel", ImGuiPopupFlags_AnyPopupLevel},
			{"ImGuiPopupFlags_AnyPopup", ImGuiPopupFlags_AnyPopup},

			//enum ImGuiSelectableFlags_
			{"ImGuiSelectableFlags_None", ImGuiSelectableFlags_None},
			{"ImGuiSelectableFlags_DontClosePopups", ImGuiSelectableFlags_DontClosePopups},
			{"ImGuiSelectableFlags_SpanAllColumns", ImGuiSelectableFlags_SpanAllColumns},
			{"ImGuiSelectableFlags_AllowDoubleClick", ImGuiSelectableFlags_AllowDoubleClick},
			{"ImGuiSelectableFlags_Disabled", ImGuiSelectableFlags_Disabled},
			{"ImGuiSelectableFlags_AllowItemOverlap", ImGuiSelectableFlags_AllowItemOverlap},

			//enum ImGuiComboFlags_
			{"ImGuiComboFlags_None", ImGuiComboFlags_None},
			{"ImGuiComboFlags_PopupAlignLeft", ImGuiComboFlags_PopupAlignLeft},
			{"ImGuiComboFlags_HeightSmall", ImGuiComboFlags_HeightSmall},
			{"ImGuiComboFlags_HeightRegular", ImGuiComboFlags_HeightRegular},
			{"ImGuiComboFlags_HeightLarge", ImGuiComboFlags_HeightLarge},
			{"ImGuiComboFlags_HeightLargest", ImGuiComboFlags_HeightLargest},
			{"ImGuiComboFlags_NoArrowButton", ImGuiComboFlags_NoArrowButton},
			{"ImGuiComboFlags_NoPreview", ImGuiComboFlags_NoPreview},
			{"ImGuiComboFlags_HeightMask_", ImGuiComboFlags_HeightMask_},

			//enum ImGuiTabBarFlags_
			{"ImGuiTabBarFlags_None", ImGuiTabBarFlags_None},
			{"ImGuiTabBarFlags_Reorderable", ImGuiTabBarFlags_Reorderable},
			{"ImGuiTabBarFlags_AutoSelectNewTabs", ImGuiTabBarFlags_AutoSelectNewTabs},
			{"ImGuiTabBarFlags_TabListPopupButton", ImGuiTabBarFlags_TabListPopupButton},
			{"ImGuiTabBarFlags_NoCloseWithMiddleMouseButton", ImGuiTabBarFlags_NoCloseWithMiddleMouseButton},
			{"ImGuiTabBarFlags_NoTabListScrollingButtons", ImGuiTabBarFlags_NoTabListScrollingButtons},
			{"ImGuiTabBarFlags_NoTooltip", ImGuiTabBarFlags_NoTooltip},
			{"ImGuiTabBarFlags_FittingPolicyResizeDown", ImGuiTabBarFlags_FittingPolicyResizeDown},
			{"ImGuiTabBarFlags_FittingPolicyScroll", ImGuiTabBarFlags_FittingPolicyScroll},
			{"ImGuiTabBarFlags_FittingPolicyMask_", ImGuiTabBarFlags_FittingPolicyMask_},
			{"ImGuiTabBarFlags_FittingPolicyDefault_", ImGuiTabBarFlags_FittingPolicyDefault_},

			//enum ImGuiTabItemFlags_
			{"ImGuiTabItemFlags_None", ImGuiTabItemFlags_None},
			{"ImGuiTabItemFlags_UnsavedDocument", ImGuiTabItemFlags_UnsavedDocument},
			{"ImGuiTabItemFlags_SetSelected", ImGuiTabItemFlags_SetSelected},
			{"ImGuiTabItemFlags_NoCloseWithMiddleMouseButton", ImGuiTabItemFlags_NoCloseWithMiddleMouseButton},
			{"ImGuiTabItemFlags_NoPushId", ImGuiTabItemFlags_NoPushId},
			{"ImGuiTabItemFlags_NoTooltip", ImGuiTabItemFlags_NoTooltip},
			{"ImGuiTabItemFlags_NoReorder", ImGuiTabItemFlags_NoReorder},
			{"ImGuiTabItemFlags_Leading", ImGuiTabItemFlags_Leading},
			{"ImGuiTabItemFlags_Trailing", ImGuiTabItemFlags_Trailing},

			// enum ImGuiTableFlags_
			{"ImGuiTableFlags_None", ImGuiTableFlags_None},
			{"ImGuiTableFlags_Resizable", ImGuiTableFlags_Resizable},
			{"ImGuiTableFlags_Reorderable", ImGuiTableFlags_Reorderable},
			{"ImGuiTableFlags_Hideable", ImGuiTableFlags_Hideable},
			{"ImGuiTableFlags_Sortable", ImGuiTableFlags_Sortable},
			{"ImGuiTableFlags_NoSavedSettings", ImGuiTableFlags_NoSavedSettings},
			{"ImGuiTableFlags_ContextMenuInBody", ImGuiTableFlags_ContextMenuInBody},
			{"ImGuiTableFlags_RowBg", ImGuiTableFlags_RowBg},
			{"ImGuiTableFlags_BordersInnerH", ImGuiTableFlags_BordersInnerH},
			{"ImGuiTableFlags_BordersOuterH", ImGuiTableFlags_BordersOuterH},
			{"ImGuiTableFlags_BordersInnerV", ImGuiTableFlags_BordersInnerV},
			{"ImGuiTableFlags_BordersOuterV", ImGuiTableFlags_BordersOuterV},
			{"ImGuiTableFlags_BordersH", ImGuiTableFlags_BordersH},
			{"ImGuiTableFlags_BordersV", ImGuiTableFlags_BordersV},
			{"ImGuiTableFlags_BordersInner", ImGuiTableFlags_BordersInner},
			{"ImGuiTableFlags_BordersOuter", ImGuiTableFlags_BordersOuter},
			{"ImGuiTableFlags_Borders", ImGuiTableFlags_Borders},
			{"ImGuiTableFlags_NoBordersInBody", ImGuiTableFlags_NoBordersInBody},
			{"ImGuiTableFlags_NoBordersInBodyUntilResize", ImGuiTableFlags_NoBordersInBodyUntilResize},
			{"ImGuiTableFlags_SizingFixedFit", ImGuiTableFlags_SizingFixedFit},
			{"ImGuiTableFlags_SizingFixedSame", ImGuiTableFlags_SizingFixedSame},
			{"ImGuiTableFlags_SizingStretchProp", ImGuiTableFlags_SizingStretchProp},
			{"ImGuiTableFlags_SizingStretchSame", ImGuiTableFlags_SizingStretchSame},
			{"ImGuiTableFlags_NoHostExtendX", ImGuiTableFlags_NoHostExtendX},
			{"ImGuiTableFlags_NoHostExtendY", ImGuiTableFlags_NoHostExtendY},
			{"ImGuiTableFlags_NoKeepColumnsVisible", ImGuiTableFlags_NoKeepColumnsVisible},
			{"ImGuiTableFlags_PreciseWidths", ImGuiTableFlags_PreciseWidths},
			{"ImGuiTableFlags_NoClip", ImGuiTableFlags_NoClip},
			{"ImGuiTableFlags_PadOuterX", ImGuiTableFlags_PadOuterX},
			{"ImGuiTableFlags_NoPadOuterX", ImGuiTableFlags_NoPadOuterX},
			{"ImGuiTableFlags_NoPadInnerX", ImGuiTableFlags_NoPadInnerX},
			{"ImGuiTableFlags_ScrollX", ImGuiTableFlags_ScrollX},
			{"ImGuiTableFlags_ScrollY", ImGuiTableFlags_ScrollY},
			{"ImGuiTableFlags_SortMulti", ImGuiTableFlags_SortMulti},
			{"ImGuiTableFlags_SortTristate", ImGuiTableFlags_SortTristate},
			{"ImGuiTableFlags_SizingMask_", ImGuiTableFlags_SizingMask_},

			//enum ImGuiTableColumnFlags_
			{"ImGuiTableColumnFlags_None", ImGuiTableColumnFlags_None},
			{"ImGuiTableColumnFlags_Disabled", ImGuiTableColumnFlags_Disabled},
			{"ImGuiTableColumnFlags_DefaultHide", ImGuiTableColumnFlags_DefaultHide},
			{"ImGuiTableColumnFlags_DefaultSort", ImGuiTableColumnFlags_DefaultSort},
			{"ImGuiTableColumnFlags_WidthStretch", ImGuiTableColumnFlags_WidthStretch},
			{"ImGuiTableColumnFlags_WidthFixed", ImGuiTableColumnFlags_WidthFixed},
			{"ImGuiTableColumnFlags_NoResize", ImGuiTableColumnFlags_NoResize},
			{"ImGuiTableColumnFlags_NoReorder", ImGuiTableColumnFlags_NoReorder},
			{"ImGuiTableColumnFlags_NoHide", ImGuiTableColumnFlags_NoHide},
			{"ImGuiTableColumnFlags_NoClip", ImGuiTableColumnFlags_NoClip},
			{"ImGuiTableColumnFlags_NoSort", ImGuiTableColumnFlags_NoSort},
			{"ImGuiTableColumnFlags_NoSortAscending", ImGuiTableColumnFlags_NoSortAscending},
			{"ImGuiTableColumnFlags_NoSortDescending", ImGuiTableColumnFlags_NoSortDescending},
			{"ImGuiTableColumnFlags_NoHeaderLabel", ImGuiTableColumnFlags_NoHeaderLabel},
			{"ImGuiTableColumnFlags_NoHeaderWidth", ImGuiTableColumnFlags_NoHeaderWidth},
			{"ImGuiTableColumnFlags_PreferSortAscending", ImGuiTableColumnFlags_PreferSortAscending},
			{"ImGuiTableColumnFlags_PreferSortDescending", ImGuiTableColumnFlags_PreferSortDescending},
			{"ImGuiTableColumnFlags_IndentEnable", ImGuiTableColumnFlags_IndentEnable},
			{"ImGuiTableColumnFlags_IndentDisable", ImGuiTableColumnFlags_IndentDisable},
			{"ImGuiTableColumnFlags_IsEnabled", ImGuiTableColumnFlags_IsEnabled},
			{"ImGuiTableColumnFlags_IsVisible", ImGuiTableColumnFlags_IsVisible},
			{"ImGuiTableColumnFlags_IsSorted", ImGuiTableColumnFlags_IsSorted},
			{"ImGuiTableColumnFlags_IsHovered", ImGuiTableColumnFlags_IsHovered},
			{"ImGuiTableColumnFlags_WidthMask_", ImGuiTableColumnFlags_WidthMask_},
			{"ImGuiTableColumnFlags_IndentMask_", ImGuiTableColumnFlags_IndentMask_},
			{"ImGuiTableColumnFlags_StatusMask_", ImGuiTableColumnFlags_StatusMask_},
			{"ImGuiTableColumnFlags_NoDirectResize_", ImGuiTableColumnFlags_NoDirectResize_},

			//enum ImGuiTableRowFlags_
			{"ImGuiTableRowFlags_None", ImGuiTableRowFlags_None},
			{"ImGuiTableRowFlags_Headers", ImGuiTableRowFlags_Headers},

			//enum ImGuiTableBgTarget_
			{"ImGuiTableBgTarget_None", ImGuiTableBgTarget_None},
			{"ImGuiTableBgTarget_RowBg0", ImGuiTableBgTarget_RowBg0},
			{"ImGuiTableBgTarget_RowBg1", ImGuiTableBgTarget_RowBg1},
			{"ImGuiTableBgTarget_CellBg", ImGuiTableBgTarget_CellBg},

			//enum ImGuiFocusedFlags_
			{"ImGuiFocusedFlags_None", ImGuiFocusedFlags_None},
			{"ImGuiFocusedFlags_ChildWindows", ImGuiFocusedFlags_ChildWindows},
			{"ImGuiFocusedFlags_RootWindow", ImGuiFocusedFlags_RootWindow},
			{"ImGuiFocusedFlags_AnyWindow", ImGuiFocusedFlags_AnyWindow},
			{"ImGuiFocusedFlags_RootAndChildWindows", ImGuiFocusedFlags_RootAndChildWindows},

			//enum ImGuiHoveredFlags_
			{"ImGuiHoveredFlags_None", ImGuiHoveredFlags_None},
			{"ImGuiHoveredFlags_ChildWindows", ImGuiHoveredFlags_ChildWindows},
			{"ImGuiHoveredFlags_RootWindow", ImGuiHoveredFlags_RootWindow},
			{"ImGuiHoveredFlags_AnyWindow", ImGuiHoveredFlags_AnyWindow},
			{"ImGuiHoveredFlags_AllowWhenBlockedByPopup", ImGuiHoveredFlags_AllowWhenBlockedByPopup},
			{"ImGuiHoveredFlags_AllowWhenBlockedByActiveItem", ImGuiHoveredFlags_AllowWhenBlockedByActiveItem},
			{"ImGuiHoveredFlags_AllowWhenOverlapped", ImGuiHoveredFlags_AllowWhenOverlapped},
			{"ImGuiHoveredFlags_AllowWhenDisabled", ImGuiHoveredFlags_AllowWhenDisabled},
			{"ImGuiHoveredFlags_RectOnly", ImGuiHoveredFlags_RectOnly},
			{"ImGuiHoveredFlags_RootAndChildWindows", ImGuiHoveredFlags_RootAndChildWindows},

			//enum ImGuiDragDropFlags_
			{"ImGuiDragDropFlags_None", ImGuiDragDropFlags_None},
			{"ImGuiDragDropFlags_SourceNoPreviewTooltip", ImGuiDragDropFlags_SourceNoPreviewTooltip},
			{"ImGuiDragDropFlags_SourceNoDisableHover", ImGuiDragDropFlags_SourceNoDisableHover},
			{"ImGuiDragDropFlags_SourceNoHoldToOpenOthers", ImGuiDragDropFlags_SourceNoHoldToOpenOthers},
			{"ImGuiDragDropFlags_SourceAllowNullID", ImGuiDragDropFlags_SourceAllowNullID},
			{"ImGuiDragDropFlags_SourceExtern", ImGuiDragDropFlags_SourceExtern},
			{"ImGuiDragDropFlags_SourceAutoExpirePayload", ImGuiDragDropFlags_SourceAutoExpirePayload},
			{"ImGuiDragDropFlags_AcceptBeforeDelivery", ImGuiDragDropFlags_AcceptBeforeDelivery},
			{"ImGuiDragDropFlags_AcceptNoDrawDefaultRect", ImGuiDragDropFlags_AcceptNoDrawDefaultRect},
			{"ImGuiDragDropFlags_AcceptNoPreviewTooltip", ImGuiDragDropFlags_AcceptNoPreviewTooltip},
			{"ImGuiDragDropFlags_AcceptPeekOnly", ImGuiDragDropFlags_AcceptPeekOnly},

			//enum ImGuiDataType_
			{"ImGuiDataType_S8", ImGuiDataType_S8},
			{"ImGuiDataType_U8", ImGuiDataType_U8},
			{"ImGuiDataType_S16", ImGuiDataType_S16},
			{"ImGuiDataType_U16", ImGuiDataType_U16},
			{"ImGuiDataType_S32", ImGuiDataType_S32},
			{"ImGuiDataType_U32", ImGuiDataType_U32},
			{"ImGuiDataType_S64", ImGuiDataType_S64},
			{"ImGuiDataType_S64", ImGuiDataType_U64},
			{"ImGuiDataType_S64", ImGuiDataType_Float},
			{"ImGuiDataType_S64", ImGuiDataType_Double},
			{"ImGuiDataType_S64", ImGuiDataType_COUNT},

			//enum ImGuiDir_
			{"ImGuiDir_None", ImGuiDir_None},
			{"ImGuiDir_Left", ImGuiDir_Left},
			{"ImGuiDir_Right", ImGuiDir_Right},
			{"ImGuiDir_Up", ImGuiDir_Up},
			{"ImGuiDir_Down", ImGuiDir_Down},
			{"ImGuiDir_COUNT", ImGuiDir_COUNT},

			//enum ImGuiSortDirection_
			{"ImGuiSortDirection_None", ImGuiSortDirection_None},
			{"ImGuiSortDirection_Ascending", ImGuiSortDirection_Ascending},
			{"ImGuiSortDirection_Descending", ImGuiSortDirection_Descending},

			//enum ImGuiKey
			{"ImGuiKey_None", ImGuiKey_None},
			{"ImGuiKey_Tab", ImGuiKey_Tab},
			{"ImGuiKey_LeftArrow", ImGuiKey_LeftArrow},
			{"ImGuiKey_RightArrow", ImGuiKey_RightArrow},
			{"ImGuiKey_UpArrow", ImGuiKey_UpArrow},
			{"ImGuiKey_DownArrow", ImGuiKey_DownArrow},
			{"ImGuiKey_PageUp", ImGuiKey_PageUp},
			{"ImGuiKey_PageDown", ImGuiKey_PageDown},
			{"ImGuiKey_Home", ImGuiKey_Home},
			{"ImGuiKey_End", ImGuiKey_End},
			{"ImGuiKey_Insert", ImGuiKey_Insert},
			{"ImGuiKey_Delete", ImGuiKey_Delete},
			{"ImGuiKey_Backspace", ImGuiKey_Backspace},
			{"ImGuiKey_Space", ImGuiKey_Space},
			{"ImGuiKey_Enter", ImGuiKey_Enter},
			{"ImGuiKey_Escape", ImGuiKey_Escape},
			{"ImGuiKey_LeftCtrl", ImGuiKey_LeftCtrl},
			{"ImGuiKey_LeftShift", ImGuiKey_LeftShift},
			{"ImGuiKey_LeftAlt", ImGuiKey_LeftAlt},
			{"ImGuiKey_LeftSuper", ImGuiKey_LeftSuper},
			{"ImGuiKey_RightCtrl", ImGuiKey_RightCtrl},
			{"ImGuiKey_RightShift", ImGuiKey_RightShift},
			{"ImGuiKey_RightAlt", ImGuiKey_RightAlt},
			{"ImGuiKey_RightSuper", ImGuiKey_RightSuper},
			{"ImGuiKey_0", ImGuiKey_0},
			{"ImGuiKey_1", ImGuiKey_1},
			{"ImGuiKey_2", ImGuiKey_2},
			{"ImGuiKey_3", ImGuiKey_3},
			{"ImGuiKey_4", ImGuiKey_4},
			{"ImGuiKey_5", ImGuiKey_5},
			{"ImGuiKey_6", ImGuiKey_6},
			{"ImGuiKey_7", ImGuiKey_7},
			{"ImGuiKey_8", ImGuiKey_8},
			{"ImGuiKey_9", ImGuiKey_9},
			{"ImGuiKey_A", ImGuiKey_A},
			{"ImGuiKey_B", ImGuiKey_B},
			{"ImGuiKey_C", ImGuiKey_C},
			{"ImGuiKey_D", ImGuiKey_D},
			{"ImGuiKey_E", ImGuiKey_E},
			{"ImGuiKey_F", ImGuiKey_F},
			{"ImGuiKey_G", ImGuiKey_G},
			{"ImGuiKey_H", ImGuiKey_H},
			{"ImGuiKey_I", ImGuiKey_I},
			{"ImGuiKey_J", ImGuiKey_J},
			{"ImGuiKey_K", ImGuiKey_K},
			{"ImGuiKey_L", ImGuiKey_L},
			{"ImGuiKey_M", ImGuiKey_M},
			{"ImGuiKey_N", ImGuiKey_N},
			{"ImGuiKey_O", ImGuiKey_O},
			{"ImGuiKey_P", ImGuiKey_P},
			{"ImGuiKey_Q", ImGuiKey_Q},
			{"ImGuiKey_R", ImGuiKey_R},
			{"ImGuiKey_S", ImGuiKey_S},
			{"ImGuiKey_T", ImGuiKey_T},
			{"ImGuiKey_U", ImGuiKey_U},
			{"ImGuiKey_V", ImGuiKey_V},
			{"ImGuiKey_W", ImGuiKey_W},
			{"ImGuiKey_X", ImGuiKey_X},
			{"ImGuiKey_Y", ImGuiKey_Y},
			{"ImGuiKey_Z", ImGuiKey_Z},
			{"ImGuiKey_Apostrophe", ImGuiKey_Apostrophe},
			{"ImGuiKey_Comma", ImGuiKey_Comma},
			{"ImGuiKey_Minus", ImGuiKey_Minus},
			{"ImGuiKey_Period", ImGuiKey_Period},
			{"ImGuiKey_Slash", ImGuiKey_Slash},
			{"ImGuiKey_Semicolon", ImGuiKey_Semicolon},
			{"ImGuiKey_Equal", ImGuiKey_Equal},
			{"ImGuiKey_LeftBracket", ImGuiKey_LeftBracket},
			{"ImGuiKey_Backslash", ImGuiKey_Backslash},
			{"ImGuiKey_RightBracket", ImGuiKey_RightBracket},
			{"ImGuiKey_GraveAccent", ImGuiKey_GraveAccent},
			{"ImGuiKey_CapsLock", ImGuiKey_CapsLock},
			{"ImGuiKey_ScrollLock", ImGuiKey_ScrollLock},
			{"ImGuiKey_NumLock", ImGuiKey_NumLock},
			{"ImGuiKey_PrintScreen", ImGuiKey_PrintScreen},
			{"ImGuiKey_Pause", ImGuiKey_Pause},
			{"ImGuiKey_Keypad0", ImGuiKey_Keypad0},
			{"ImGuiKey_Keypad1", ImGuiKey_Keypad1},
			{"ImGuiKey_Keypad2", ImGuiKey_Keypad2},
			{"ImGuiKey_Keypad3", ImGuiKey_Keypad3},
			{"ImGuiKey_Keypad4", ImGuiKey_Keypad4},
			{"ImGuiKey_Keypad5", ImGuiKey_Keypad5},
			{"ImGuiKey_Keypad6", ImGuiKey_Keypad6},
			{"ImGuiKey_Keypad7", ImGuiKey_Keypad7},
			{"ImGuiKey_Keypad8", ImGuiKey_Keypad8},
			{"ImGuiKey_Keypad9", ImGuiKey_Keypad9},
			{"ImGuiKey_KeypadDecimal", ImGuiKey_KeypadDecimal},
			{"ImGuiKey_KeypadDivide", ImGuiKey_KeypadDivide},
			{"ImGuiKey_KeypadMultiply", ImGuiKey_KeypadMultiply},
			{"ImGuiKey_KeypadSubtract", ImGuiKey_KeypadSubtract},
			{"ImGuiKey_KeypadAdd", ImGuiKey_KeypadAdd},
			{"ImGuiKey_KeypadEnter", ImGuiKey_KeypadEnter},
			{"ImGuiKey_KeypadEqual", ImGuiKey_KeypadEqual},
			{"ImGuiKey_GamepadStart", ImGuiKey_GamepadStart},
			{"ImGuiKey_GamepadBack", ImGuiKey_GamepadBack},
			{"ImGuiKey_GamepadFaceLeft", ImGuiKey_GamepadFaceLeft},
			{"ImGuiKey_GamepadFaceRight", ImGuiKey_GamepadFaceRight},
			{"ImGuiKey_GamepadFaceUp", ImGuiKey_GamepadFaceUp},
			{"ImGuiKey_GamepadFaceDown", ImGuiKey_GamepadFaceDown},
			{"ImGuiKey_GamepadDpadLeft", ImGuiKey_GamepadDpadLeft},
			{"ImGuiKey_GamepadDpadRight", ImGuiKey_GamepadDpadRight},
			{"ImGuiKey_GamepadDpadUp", ImGuiKey_GamepadDpadUp},
			{"ImGuiKey_GamepadDpadDown", ImGuiKey_GamepadDpadDown},
			{"ImGuiKey_GamepadL1", ImGuiKey_GamepadL1},
			{"ImGuiKey_GamepadR1", ImGuiKey_GamepadR1},
			{"ImGuiKey_GamepadL2", ImGuiKey_GamepadL2},
			{"ImGuiKey_GamepadR2", ImGuiKey_GamepadR2},
			{"ImGuiKey_GamepadL3", ImGuiKey_GamepadL3},
			{"ImGuiKey_GamepadR3", ImGuiKey_GamepadR3},
			{"ImGuiKey_GamepadLStickLeft", ImGuiKey_GamepadLStickLeft},
			{"ImGuiKey_GamepadLStickRight", ImGuiKey_GamepadLStickRight},
			{"ImGuiKey_GamepadLStickUp", ImGuiKey_GamepadLStickUp},
			{"ImGuiKey_GamepadLStickDown", ImGuiKey_GamepadLStickDown},
			{"ImGuiKey_GamepadRStickLeft", ImGuiKey_GamepadRStickLeft},
			{"ImGuiKey_GamepadRStickRight", ImGuiKey_GamepadRStickRight},
			{"ImGuiKey_GamepadRStickUp", ImGuiKey_GamepadRStickUp},
			{"ImGuiKey_GamepadRStickDown", ImGuiKey_GamepadRStickDown},
			{"ImGuiKey_MouseLeft", ImGuiKey_MouseLeft},
			{"ImGuiKey_MouseRight", ImGuiKey_MouseRight},
			{"ImGuiKey_MouseMiddle", ImGuiKey_MouseMiddle},
			{"ImGuiKey_MouseX1", ImGuiKey_MouseX1},
			{"ImGuiKey_MouseX2", ImGuiKey_MouseX2},
			{"ImGuiKey_MouseWheelX", ImGuiKey_MouseWheelX},
			{"ImGuiKey_MouseWheelY", ImGuiKey_MouseWheelY},
			{"ImGuiKey_ReservedForModCtrl", ImGuiKey_ReservedForModCtrl},
			{"ImGuiKey_ReservedForModShift", ImGuiKey_ReservedForModShift},
			{"ImGuiKey_ReservedForModAlt", ImGuiKey_ReservedForModAlt},
			{"ImGuiKey_ReservedForModSuper", ImGuiKey_ReservedForModSuper},
			{"ImGuiKey_COUNT", ImGuiKey_COUNT},
			{"ImGuiMod_None", ImGuiMod_None},
			{"ImGuiMod_Ctrl", ImGuiMod_Ctrl},
			{"ImGuiMod_Shift", ImGuiMod_Shift},
			{"ImGuiMod_Alt", ImGuiMod_Alt},
			{"ImGuiMod_Super", ImGuiMod_Super},
			{"ImGuiMod_Shortcut", ImGuiMod_Shortcut},
			{"ImGuiMod_Mask_", ImGuiMod_Mask_},
			{"ImGuiKey_NamedKey_BEGIN", ImGuiKey_NamedKey_BEGIN},
			{"ImGuiKey_NamedKey_END", ImGuiKey_NamedKey_END},
			{"ImGuiKey_NamedKey_COUNT", ImGuiKey_NamedKey_COUNT},
			{"ImGuiKey_KeysData_SIZE", ImGuiKey_KeysData_SIZE},
			{"ImGuiKey_KeysData_OFFSET", ImGuiKey_KeysData_OFFSET},
			{"ImGuiKey_ModCtrl", ImGuiKey_ModCtrl},

			//enum ImGuiNavInput
			{"ImGuiNavInput_Activate", ImGuiNavInput_Activate},
			{"ImGuiNavInput_Cancel", ImGuiNavInput_Cancel},
			{"ImGuiNavInput_Input", ImGuiNavInput_Input},
			{"ImGuiNavInput_Menu", ImGuiNavInput_Menu},
			{"ImGuiNavInput_DpadLeft", ImGuiNavInput_DpadLeft},
			{"ImGuiNavInput_DpadRight", ImGuiNavInput_DpadRight},
			{"ImGuiNavInput_DpadUp", ImGuiNavInput_DpadUp},
			{"ImGuiNavInput_DpadDown", ImGuiNavInput_DpadDown},
			{"ImGuiNavInput_LStickLeft", ImGuiNavInput_LStickLeft},
			{"ImGuiNavInput_LStickRight", ImGuiNavInput_LStickRight},
			{"ImGuiNavInput_LStickUp", ImGuiNavInput_LStickUp},
			{"ImGuiNavInput_LStickDown", ImGuiNavInput_LStickDown},
			{"ImGuiNavInput_FocusPrev", ImGuiNavInput_FocusPrev},
			{"ImGuiNavInput_FocusNext", ImGuiNavInput_FocusNext},
			{"ImGuiNavInput_TweakSlow", ImGuiNavInput_TweakSlow},
			{"ImGuiNavInput_TweakFast", ImGuiNavInput_TweakFast},
			{"ImGuiNavInput_COUNT", ImGuiNavInput_COUNT},

			//enum ImGuiConfigFlags_
			{"ImGuiConfigFlags_None", ImGuiConfigFlags_None},
			{"ImGuiConfigFlags_NavEnableKeyboard", ImGuiConfigFlags_NavEnableKeyboard},
			{"ImGuiConfigFlags_NavEnableGamepad", ImGuiConfigFlags_NavEnableGamepad},
			{"ImGuiConfigFlags_NavEnableSetMousePos", ImGuiConfigFlags_NavEnableSetMousePos},
			{"ImGuiConfigFlags_NavNoCaptureKeyboard", ImGuiConfigFlags_NavNoCaptureKeyboard},
			{"ImGuiConfigFlags_NoMouse", ImGuiConfigFlags_NoMouse},
			{"ImGuiConfigFlags_NoMouseCursorChange", ImGuiConfigFlags_NoMouseCursorChange},
			{"ImGuiConfigFlags_IsSRGB", ImGuiConfigFlags_IsSRGB},
			{"ImGuiConfigFlags_IsTouchScreen", ImGuiConfigFlags_IsTouchScreen},

			//enum ImGuiBackendFlags_
			{"ImGuiBackendFlags_None", ImGuiBackendFlags_None},
			{"ImGuiBackendFlags_HasGamepad", ImGuiBackendFlags_HasGamepad},
			{"ImGuiBackendFlags_HasMouseCursors", ImGuiBackendFlags_HasMouseCursors},
			{"ImGuiBackendFlags_HasSetMousePos", ImGuiBackendFlags_HasSetMousePos},
			{"ImGuiBackendFlags_RendererHasVtxOffset", ImGuiBackendFlags_RendererHasVtxOffset},

			//enum ImGuiCol_
			{"ImGuiCol_Text", ImGuiCol_Text},
			{"ImGuiCol_TextDisabled", ImGuiCol_TextDisabled},
			{"ImGuiCol_WindowBg", ImGuiCol_WindowBg},
			{"ImGuiCol_ChildBg", ImGuiCol_ChildBg},
			{"ImGuiCol_PopupBg", ImGuiCol_PopupBg},
			{"ImGuiCol_Border", ImGuiCol_Border},
			{"ImGuiCol_BorderShadow", ImGuiCol_BorderShadow},
			{"ImGuiCol_FrameBg", ImGuiCol_FrameBg},
			{"ImGuiCol_FrameBgHovered", ImGuiCol_FrameBgHovered},
			{"ImGuiCol_FrameBgActive", ImGuiCol_FrameBgActive},
			{"ImGuiCol_TitleBg", ImGuiCol_TitleBg},
			{"ImGuiCol_TitleBgActive", ImGuiCol_TitleBgActive},
			{"ImGuiCol_TitleBgCollapsed", ImGuiCol_TitleBgCollapsed},
			{"ImGuiCol_MenuBarBg", ImGuiCol_MenuBarBg},
			{"ImGuiCol_ScrollbarBg", ImGuiCol_ScrollbarBg},
			{"ImGuiCol_ScrollbarGrab", ImGuiCol_ScrollbarGrab},
			{"ImGuiCol_ScrollbarGrabHovered", ImGuiCol_ScrollbarGrabHovered},
			{"ImGuiCol_ScrollbarGrabActive", ImGuiCol_ScrollbarGrabActive},
			{"ImGuiCol_CheckMark", ImGuiCol_CheckMark},
			{"ImGuiCol_SliderGrab", ImGuiCol_SliderGrab},
			{"ImGuiCol_SliderGrabActive", ImGuiCol_SliderGrabActive},
			{"ImGuiCol_Button", ImGuiCol_Button},
			{"ImGuiCol_ButtonHovered", ImGuiCol_ButtonHovered},
			{"ImGuiCol_ButtonActive", ImGuiCol_ButtonActive},
			{"ImGuiCol_Header", ImGuiCol_Header},
			{"ImGuiCol_HeaderHovered", ImGuiCol_HeaderHovered},
			{"ImGuiCol_HeaderActive", ImGuiCol_HeaderActive},
			{"ImGuiCol_Separator", ImGuiCol_Separator},
			{"ImGuiCol_SeparatorHovered", ImGuiCol_SeparatorHovered},
			{"ImGuiCol_SeparatorActive", ImGuiCol_SeparatorActive},
			{"ImGuiCol_ResizeGrip", ImGuiCol_ResizeGrip},
			{"ImGuiCol_ResizeGripHovered", ImGuiCol_ResizeGripHovered},
			{"ImGuiCol_ResizeGripActive", ImGuiCol_ResizeGripActive},
			{"ImGuiCol_Tab", ImGuiCol_Tab},
			{"ImGuiCol_TabHovered", ImGuiCol_TabHovered},
			{"ImGuiCol_TabActive", ImGuiCol_TabActive},
			{"ImGuiCol_TabUnfocused", ImGuiCol_TabUnfocused},
			{"ImGuiCol_TabUnfocusedActive", ImGuiCol_TabUnfocusedActive},
			{"ImGuiCol_PlotLines", ImGuiCol_PlotLines},
			{"ImGuiCol_PlotHistogram", ImGuiCol_PlotHistogram},
			{"ImGuiCol_PlotHistogramHovered", ImGuiCol_PlotHistogramHovered},
			{"ImGuiCol_TableHeaderBg", ImGuiCol_TableHeaderBg},
			{"ImGuiCol_TableBorderStrong", ImGuiCol_TableBorderStrong},
			{"ImGuiCol_PlotLinesHovered", ImGuiCol_PlotLinesHovered},
			{"ImGuiCol_TableBorderLight", ImGuiCol_TableBorderLight},
			{"ImGuiCol_TableRowBg", ImGuiCol_TableRowBg},
			{"ImGuiCol_TableRowBgAlt", ImGuiCol_TableRowBgAlt},
			{"ImGuiCol_TextSelectedBg", ImGuiCol_TextSelectedBg},
			{"ImGuiCol_DragDropTarget", ImGuiCol_DragDropTarget},
			{"ImGuiCol_NavHighlight", ImGuiCol_NavHighlight},
			{"ImGuiCol_NavWindowingHighlight", ImGuiCol_NavWindowingHighlight},
			{"ImGuiCol_NavWindowingDimBg", ImGuiCol_NavWindowingDimBg},
			{"ImGuiCol_ModalWindowDimBg", ImGuiCol_ModalWindowDimBg},
			{"ImGuiCol_COUNT", ImGuiCol_COUNT},

			//enum ImGuiStyleVar_
			{"ImGuiStyleVar_Alpha", ImGuiStyleVar_Alpha},
			{"ImGuiStyleVar_DisabledAlpha", ImGuiStyleVar_DisabledAlpha},
			{"ImGuiStyleVar_WindowPadding", ImGuiStyleVar_WindowPadding},
			{"ImGuiStyleVar_WindowRounding", ImGuiStyleVar_WindowRounding},
			{"ImGuiStyleVar_WindowBorderSize", ImGuiStyleVar_WindowBorderSize},
			{"ImGuiStyleVar_WindowMinSize", ImGuiStyleVar_WindowMinSize},
			{"ImGuiStyleVar_WindowTitleAlign", ImGuiStyleVar_WindowTitleAlign},
			{"ImGuiStyleVar_ChildRounding", ImGuiStyleVar_ChildRounding},
			{"ImGuiStyleVar_ChildBorderSize", ImGuiStyleVar_ChildBorderSize},
			{"ImGuiStyleVar_PopupRounding", ImGuiStyleVar_PopupRounding},
			{"ImGuiStyleVar_PopupBorderSize", ImGuiStyleVar_PopupBorderSize},
			{"ImGuiStyleVar_FramePadding", ImGuiStyleVar_FramePadding},
			{"ImGuiStyleVar_FrameRounding", ImGuiStyleVar_FrameRounding},
			{"ImGuiStyleVar_FrameBorderSize", ImGuiStyleVar_FrameBorderSize},
			{"ImGuiStyleVar_ItemSpacing", ImGuiStyleVar_ItemSpacing},
			{"ImGuiStyleVar_ItemInnerSpacing", ImGuiStyleVar_ItemInnerSpacing},
			{"ImGuiStyleVar_IndentSpacing", ImGuiStyleVar_IndentSpacing},
			{"ImGuiStyleVar_CellPadding", ImGuiStyleVar_CellPadding},
			{"ImGuiStyleVar_ScrollbarSize", ImGuiStyleVar_ScrollbarSize},
			{"ImGuiStyleVar_ScrollbarRounding", ImGuiStyleVar_ScrollbarRounding},
			{"ImGuiStyleVar_GrabMinSize", ImGuiStyleVar_GrabMinSize},
			{"ImGuiStyleVar_GrabRounding", ImGuiStyleVar_GrabRounding},
			{"ImGuiStyleVar_TabRounding", ImGuiStyleVar_TabRounding},
			{"ImGuiStyleVar_ButtonTextAlign", ImGuiStyleVar_ButtonTextAlign},
			{"ImGuiStyleVar_SelectableTextAlign", ImGuiStyleVar_SelectableTextAlign},
			{"ImGuiStyleVar_SeparatorTextBorderSize", ImGuiStyleVar_SeparatorTextBorderSize},
			{"ImGuiStyleVar_SeparatorTextAlign", ImGuiStyleVar_SeparatorTextAlign},
			{"ImGuiStyleVar_SeparatorTextPadding", ImGuiStyleVar_SeparatorTextPadding},
			{"ImGuiStyleVar_COUNT", ImGuiStyleVar_COUNT},

			//enum ImGuiButtonFlags_
			{"ImGuiButtonFlags_None", ImGuiButtonFlags_None},
			{"ImGuiButtonFlags_MouseButtonLeft", ImGuiButtonFlags_MouseButtonLeft},
			{"ImGuiButtonFlags_MouseButtonRight", ImGuiButtonFlags_MouseButtonRight},
			{"ImGuiButtonFlags_MouseButtonMiddle", ImGuiButtonFlags_MouseButtonMiddle},
			{"ImGuiButtonFlags_MouseButtonMask_", ImGuiButtonFlags_MouseButtonMask_},
			{"ImGuiButtonFlags_MouseButtonDefault_", ImGuiButtonFlags_MouseButtonDefault_},
			
			//enum ImGuiColorEditFlags_
			{"ImGuiColorEditFlags_None", ImGuiColorEditFlags_None},
			{"ImGuiColorEditFlags_NoAlpha", ImGuiColorEditFlags_NoAlpha},
			{"ImGuiColorEditFlags_NoPicker", ImGuiColorEditFlags_NoPicker},
			{"ImGuiColorEditFlags_NoOptions", ImGuiColorEditFlags_NoOptions},
			{"ImGuiColorEditFlags_NoSmallPreview", ImGuiColorEditFlags_NoSmallPreview},
			{"ImGuiColorEditFlags_NoInputs", ImGuiColorEditFlags_NoInputs},
			{"ImGuiColorEditFlags_NoTooltip", ImGuiColorEditFlags_NoTooltip},
			{"ImGuiColorEditFlags_NoLabel", ImGuiColorEditFlags_NoLabel},
			{"ImGuiColorEditFlags_NoSidePreview", ImGuiColorEditFlags_NoSidePreview},
			{"ImGuiColorEditFlags_NoDragDrop", ImGuiColorEditFlags_NoDragDrop},
			{"ImGuiColorEditFlags_NoBorder", ImGuiColorEditFlags_NoBorder},
			{"ImGuiColorEditFlags_AlphaBar", ImGuiColorEditFlags_AlphaBar},
			{"ImGuiColorEditFlags_AlphaPreview", ImGuiColorEditFlags_AlphaPreview},
			{"ImGuiColorEditFlags_AlphaPreviewHalf", ImGuiColorEditFlags_AlphaPreviewHalf},
			{"ImGuiColorEditFlags_HDR", ImGuiColorEditFlags_HDR},
			{"ImGuiColorEditFlags_DisplayRGB", ImGuiColorEditFlags_DisplayRGB},
			{"ImGuiColorEditFlags_DisplayHSV", ImGuiColorEditFlags_DisplayHSV},
			{"ImGuiColorEditFlags_DisplayHex", ImGuiColorEditFlags_DisplayHex},
			{"ImGuiColorEditFlags_Uint8", ImGuiColorEditFlags_Uint8},
			{"ImGuiColorEditFlags_Float", ImGuiColorEditFlags_Float},
			{"ImGuiColorEditFlags_PickerHueBar", ImGuiColorEditFlags_PickerHueBar},
			{"ImGuiColorEditFlags_PickerHueWheel", ImGuiColorEditFlags_PickerHueWheel},
			{"ImGuiColorEditFlags_InputRGB", ImGuiColorEditFlags_InputRGB},
			{"ImGuiColorEditFlags_InputHSV", ImGuiColorEditFlags_InputHSV},
			{"ImGuiColorEditFlags_DefaultOptions_", ImGuiColorEditFlags_DefaultOptions_},
			{"ImGuiColorEditFlags_DisplayMask_", ImGuiColorEditFlags_DisplayMask_},
			{"ImGuiColorEditFlags_DataTypeMask_", ImGuiColorEditFlags_DataTypeMask_},
			{"ImGuiColorEditFlags_PickerMask_", ImGuiColorEditFlags_PickerMask_},
			{"ImGuiColorEditFlags_InputMask_", ImGuiColorEditFlags_InputMask_},

			//enum ImGuiSliderFlags_
			{"ImGuiSliderFlags_None", ImGuiSliderFlags_None},
			{"ImGuiSliderFlags_AlwaysClamp", ImGuiSliderFlags_AlwaysClamp},
			{"ImGuiSliderFlags_Logarithmic", ImGuiSliderFlags_Logarithmic},
			{"ImGuiSliderFlags_NoRoundToFormat", ImGuiSliderFlags_NoRoundToFormat},
			{"ImGuiSliderFlags_NoInput", ImGuiSliderFlags_NoInput},
			{"ImGuiSliderFlags_InvalidMask_", ImGuiSliderFlags_InvalidMask_},

			//enum ImGuiMouseButton_
			{"ImGuiMouseButton_Left", ImGuiMouseButton_Left},
			{"ImGuiMouseButton_Right", ImGuiMouseButton_Right},
			{"ImGuiMouseButton_Middle", ImGuiMouseButton_Middle},
			{"ImGuiMouseButton_COUNT", ImGuiMouseButton_COUNT},

			//enum ImGuiMouseCursor_			
			{"ImGuiMouseCursor_None", ImGuiMouseCursor_None},
			{"ImGuiMouseCursor_Arrow", ImGuiMouseCursor_Arrow},
			{"ImGuiMouseCursor_TextInput", ImGuiMouseCursor_TextInput},
			{"ImGuiMouseCursor_ResizeAll", ImGuiMouseCursor_ResizeAll},
			{"ImGuiMouseCursor_ResizeNS", ImGuiMouseCursor_ResizeNS},
			{"ImGuiMouseCursor_ResizeEW", ImGuiMouseCursor_ResizeEW},
			{"ImGuiMouseCursor_ResizeNESW", ImGuiMouseCursor_ResizeNESW},
			{"ImGuiMouseCursor_ResizeNWSE", ImGuiMouseCursor_ResizeNWSE},
			{"ImGuiMouseCursor_Hand", ImGuiMouseCursor_Hand},
			{"ImGuiMouseCursor_NotAllowed", ImGuiMouseCursor_NotAllowed},
			{"ImGuiMouseCursor_COUNT", ImGuiMouseCursor_COUNT},

			//enum ImGuiMouseSource
			{"ImGuiMouseSource_Mouse", ImGuiMouseSource_Mouse},
			{"ImGuiMouseSource_TouchScreen", ImGuiMouseSource_TouchScreen},
			{"ImGuiMouseSource_Pen", ImGuiMouseSource_Pen},
			{"ImGuiMouseSource_COUNT", ImGuiMouseSource_COUNT},

			//enum ImGuiCond_
			{"ImGuiCond_None", ImGuiCond_None},
			{"ImGuiCond_Always", ImGuiCond_Always},
			{"ImGuiCond_Once", ImGuiCond_Once},
			{"ImGuiCond_FirstUseEver", ImGuiCond_FirstUseEver},
			{"ImGuiCond_Appearing", ImGuiCond_Appearing}
		};

		int flag = 0;
		std::istringstream iss(str);
		std::string token;
		
		while (std::getline(iss, token, '|')) {
			// Trim any leading or trailing whitespaces from the flag token
			size_t firstNonSpace = token.find_first_not_of(' ');
			size_t lastNonSpace = token.find_last_not_of(' ');
			if (firstNonSpace != std::string::npos && lastNonSpace != std::string::npos) {
				
				std::string strFlag = token.substr(firstNonSpace, lastNonSpace - firstNonSpace + 1);
				auto it = map.find(strFlag);
				if (it == map.end()){
					CLOG(INFO, "Engine.Graphics.GUI") << "Cannot reconize : " << strFlag << " ImGui flag : set as null";
					continue;
				}

				flag |= it->second;
			}
		}

		return flag;
	}
	
}